// fx.ts — static country-to-currency mapping + display names

export const countryToCurrency: Record<string, string> = {
  "Afghanistan": "AFN",
  "Albania": "ALL",
  "Algeria": "DZD",
  "Andorra": "EUR",
  "Angola": "AOA",
  "Argentina": "ARS",
  "Armenia": "AMD",
  "Australia": "AUD",
  "Austria": "EUR",
  "Azerbaijan": "AZN",
  "Bahamas": "BSD",
  "Bahrain": "BHD",
  "Bangladesh": "BDT",
  "Barbados": "BBD",
  "Belarus": "BYN",
  "Belgium": "EUR",
  "Belize": "BZD",
  "Benin": "XOF",
  "Bhutan": "BTN",
  "Bolivia": "BOB",
  "Bosnia and Herzegovina": "BAM",
  "Botswana": "BWP",
  "Brazil": "BRL",
  "Brunei": "BND",
  "Bulgaria": "BGN",
  "Burkina Faso": "XOF",
  "Burundi": "BIF",
  "Cambodia": "KHR",
  "Cameroon": "XAF",
  "Canada": "CAD",
  "Cape Verde": "CVE",
  "Chile": "CLP",
  "China": "CNY",
  "Colombia": "COP",
  "Congo": "XAF",
  "Costa Rica": "CRC",
  "Croatia": "EUR",
  "Cuba": "CUP",
  "Cyprus": "EUR",
  "Czech Republic": "CZK",
  "Denmark": "DKK",
  "Dominican Republic": "DOP",
  "Ecuador": "USD",
  "Egypt": "EGP",
  "El Salvador": "USD",
  "Estonia": "EUR",
  "Eswatini": "SZL",
  "Ethiopia": "ETB",
  "Fiji": "FJD",
  "Finland": "EUR",
  "France": "EUR",
  "Gabon": "XAF",
  "Gambia": "GMD",
  "Georgia": "GEL",
  "Germany": "EUR",
  "Ghana": "GHS",
  "Greece": "EUR",
  "Guatemala": "GTQ",
  "Guinea": "GNF",
  "Guyana": "GYD",
  "Haiti": "HTG",
  "Honduras": "HNL",
  "Hungary": "HUF",
  "Iceland": "ISK",
  "India": "INR",
  "Indonesia": "IDR",
  "Iran": "IRR",
  "Iraq": "IQD",
  "Ireland": "EUR",
  "Israel": "ILS",
  "Italy": "EUR",
  "Jamaica": "JMD",
  "Japan": "JPY",
  "Jordan": "JOD",
  "Kazakhstan": "KZT",
  "Kenya": "KES",
  "Kuwait": "KWD",
  "Kyrgyzstan": "KGS",
  "Laos": "LAK",
  "Latvia": "EUR",
  "Lebanon": "LBP",
  "Lesotho": "LSL",
  "Liberia": "LRD",
  "Libya": "LYD",
  "Lithuania": "EUR",
  "Luxembourg": "EUR",
  "Madagascar": "MGA",
  "Malawi": "MWK",
  "Malaysia": "MYR",
  "Maldives": "MVR",
  "Mali": "XOF",
  "Malta": "EUR",
  "Mauritius": "MUR",
  "Mexico": "MXN",
  "Moldova": "MDL",
  "Monaco": "EUR",
  "Mongolia": "MNT",
  "Montenegro": "EUR",
  "Morocco": "MAD",
  "Mozambique": "MZN",
  "Myanmar": "MMK",
  "Namibia": "NAD",
  "Nepal": "NPR",
  "Netherlands": "EUR",
  "New Zealand": "NZD",
  "Nicaragua": "NIO",
  "Niger": "XOF",
  "Nigeria": "NGN",
  "North Korea": "KPW",
  "Norway": "NOK",
  "Oman": "OMR",
  "Pakistan": "PKR",
  "Palestine": "ILS",
  "Panama": "PAB",
  "Papua New Guinea": "PGK",
  "Paraguay": "PYG",
  "Peru": "PEN",
  "Philippines": "PHP",
  "Poland": "PLN",
  "Portugal": "EUR",
  "Qatar": "QAR",
  "Romania": "RON",
  "Russia": "RUB",
  "Rwanda": "RWF",
  "Saudi Arabia": "SAR",
  "Senegal": "XOF",
  "Serbia": "RSD",
  "Seychelles": "SCR",
  "Sierra Leone": "SLL",
  "Singapore": "SGD",
  "Slovakia": "EUR",
  "Slovenia": "EUR",
  "South Africa": "ZAR",
  "South Korea": "KRW",
  "Spain": "EUR",
  "Sri Lanka": "LKR",
  "Sweden": "SEK",
  "Switzerland": "CHF",
  "Syria": "SYP",
  "Taiwan": "TWD",
  "Tanzania": "TZS",
  "Thailand": "THB",
  "Togo": "XOF",
  "Trinidad and Tobago": "TTD",
  "Tunisia": "TND",
  "Turkey": "TRY",
  "Uganda": "UGX",
  "Ukraine": "UAH",
  "United Arab Emirates": "AED",
  "United Kingdom": "GBP",
  "United States": "USD",
  "Uruguay": "UYU",
  "Uzbekistan": "UZS",
  "Venezuela": "VES",
  "Vietnam": "VND",
  "Zambia": "ZMW",
  "Zimbabwe": "ZWL"
}

/** Helper to get currency code safely */
export const getCurrencyCode = (countryName?: string): string => {
  if (!countryName) return "USD"
  return countryToCurrency[countryName] || "USD"
}

/** Universal currency name resolver (covers all ISO-4217) */
let currencyDisplay: Intl.DisplayNames | undefined

try {
  if (
    typeof Intl !== "undefined" &&
    typeof (Intl as unknown as { DisplayNames?: typeof Intl.DisplayNames }).DisplayNames !== "undefined"
  ) {
    currencyDisplay = new Intl.DisplayNames(["en"], { type: "currency" })
  }
} catch {
  // ignore; fallback below
}


export const getCurrencyName = (code?: string): string => {
  if (!code) return "US Dollar"
  const c = code.toUpperCase()
  return currencyDisplay?.of(c) || c  // fallback to code if the environment lacks support
}
