export const countries = [
  "United States",
  "China",
  "Germany",
  "Japan",
  "United Kingdom",
  "France",
  "India",
  "Italy",
  "Brazil",
  "Canada",
  "Russia",
  "South Korea",
  "Australia",
  "Spain",
  "Mexico",
  "Indonesia",
  "Netherlands",
  "Saudi Arabia",
  "Turkey",
  "Taiwan",
  "Belgium",
  "Argentina",
  "Thailand",
  "Ireland",
]

export const agriculturalProducts = [
  "Rice",
  "Corn",
  "Wheat",
  "Soybeans",
  "Barley",
  "Oats",
  "Sugar",
  "Coffee",
  "Tea",
  "Cocoa",
  "Cotton",
  "Tobacco",
  "Fruits",
  "Vegetables",
  "Beef",
  "Pork",
  "Poultry",
  "Dairy Products",
  "Fish",
  "Nuts",
]

export const currencies = {
  "United States": "USD",
  China: "CNY",
  Germany: "EUR",
  Japan: "JPY",
  "United Kingdom": "GBP",
  France: "EUR",
  India: "INR",
  Italy: "EUR",
  Brazil: "BRL",
  Canada: "CAD",
  Russia: "RUB",
  "South Korea": "KRW",
  Australia: "AUD",
  Spain: "EUR",
  Mexico: "MXN",
  Indonesia: "IDR",
  Netherlands: "EUR",
  "Saudi Arabia": "SAR",
  Turkey: "TRY",
  Taiwan: "TWD",
  Belgium: "EUR",
  Argentina: "ARS",
  Thailand: "THB",
  Ireland: "EUR",
} as const