export const countries = [
  { code: "000", name: "World" },
  { code: "840", name: "United States" },
  { code: "156", name: "China" },
  { code: "276", name: "Germany" },
  { code: "392", name: "Japan" },
  { code: "826", name: "United Kingdom" },
  { code: "250", name: "France" },
  { code: "356", name: "India" },
  { code: "380", name: "Italy" },
  { code: "076", name: "Brazil" },
  { code: "124", name: "Canada" },
  { code: "643", name: "Russia" },
  { code: "410", name: "South Korea" },
  { code: "036", name: "Australia" },
  { code: "724", name: "Spain" },
  { code: "484", name: "Mexico" },
  { code: "360", name: "Indonesia" },
  { code: "528", name: "Netherlands" },
  { code: "682", name: "Saudi Arabia" },
  { code: "792", name: "Turkey" },
  { code: "158", name: "Taiwan" },
  { code: "056", name: "Belgium" },
  { code: "032", name: "Argentina" },
  { code: "764", name: "Thailand" },
  { code: "372", name: "Ireland" },
  { code: "0000", name: "Test Dummy Entry"}
];

export const agriculturalProducts = [
  { name: "Husked (brown) rice", hs_code: "100610" },
  { name: "Milled/polished rice", hs_code: "100620" },
  { name: "Broken rice", hs_code: "100630" },
  { name: "Paddy rice", hs_code: "100640" },
  // Two random products
  { name: "Corn", hs_code: "100590" },
  { name: "Wheat", hs_code: "100190" },
]

export const currencies = {
  "United States": "USD",
  China: "CNY",
  Germany: "EUR",
  Japan: "JPY",
  "United Kingdom": "GBP",
  France: "EUR",
  India: "INR",
  Italy: "EUR",
  Brazil: "BRL",
  Canada: "CAD",
  Russia: "RUB",
  "South Korea": "KRW",
  Australia: "AUD",
  Spain: "EUR",
  Mexico: "MXN",
  Indonesia: "IDR",
  Netherlands: "EUR",
  "Saudi Arabia": "SAR",
  Turkey: "TRY",
  Taiwan: "TWD",
  Belgium: "EUR",
  Argentina: "ARS",
  Thailand: "THB",
  Ireland: "EUR",
} as const